# ---Stage 1: Build dependencies
FROM python:3.11-slim AS builder

ENV PYTHONBUFFERED=1\
    PYTHONWRITEBYTECODE=1

WORKDIR /build

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install -r requirements.txt

# ---Stage 2: Build Application Image
FROM python:3.11-slim

ENV PYTHONBUFFERED=1 \
    PYTHONWRITEBYTECODE=1 \
    PATH="/opt/venv/bin:$PATH"

ARG APP_HOME="/voting_app_backend"

WORKDIR $APP_HOME

RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser
RUN chown -R appuser:appgroup $APP_HOME

USER appuser

COPY --from=builder --chown=appuser:appgroup /opt/venv /opt/venv
COPY --chown=appuser:appgroup ./app ./app

EXPOSE 8000

ENTRYPOINT ["uvicorn"]
CMD ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]

